n = input("digite qualquer coisa: ")
print("o tipo primitivo do valor digitado por voce é", type(n))
print("o valor é um decimal?", n.isdecimal())
print("o valor digitado possui algum numero?", n.isalnum())
print("so a numero no valor digitado?", n.isnumeric())
