frase = str(input("digite seu nome completo: "))
m = frase.upper()
mm = frase.lower()
mmm = frase.split()
mmmm = frase.replace(" ", "")
print("=" * 60)
print("Seu nome em letra maiuscula: {}".format(m))
print("Seu nome em minusculas: {}".format(mm))
print("Quantas letras tem seu nome completo sem espaços: {}".format(len(mmmm)))
print("Quantas letras tem o seu primeiro nome: {}".format(len(mmm[0])))
print("=" * 60)
